POST http://localhost:3002/api/notes
Content-Type: application/json

{
    "Content":"User id of the note is sent along with the request",
    "important":true,
    "userId":"6719f63800cbed246383a5f6"
}