POST http://localhost:3002/api/notes
Content-Type: application/json

{
    "Content":"User id of the note is sent along with the request",
    "important":true,
    "userId":"67199921eec0affa2398e270"
}